import { useRef } from "react";
import { X, Printer } from "lucide-react";
import { printNode } from "../utils/printDocument";
import { Modal } from "./Modal";

const PRINTABLE_TYPES = new Set([
  "sales_invoice",
  "sales_receipt",
  "return_receipt",
  "damage_report",
  "inventory_report",
  "sales_report",
]);

export function orderReportType(status) {
  if (status === "successful") return "sales_receipt";
  if (status === "returned") return "return_receipt";
  return "sales_invoice";
}

export function hasPrintableActivity(log) {
  if (!log?.reportType || !PRINTABLE_TYPES.has(log.reportType)) return false;
  if (
    log.reportType === "sales_invoice" ||
    log.reportType === "sales_receipt" ||
    log.reportType === "return_receipt" ||
    log.reportType === "damage_report"
  ) {
    return Boolean(log.reportRefId);
  }
  if (log.reportType === "inventory_report" || log.reportType === "sales_report") {
    return Boolean(log.metadata);
  }
  return false;
}

function formatDate(value) {
  if (!value) return "—";
  return String(value).slice(0, 10);
}

function formatDateTime(value) {
  if (!value) return "—";
  return new Date(value).toLocaleString("en-PH", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export function PrintableReport({ type, data, generatedBy, onClose, title: titleOverride }) {
  const printRef = useRef(null);
  if (!data) return null;

  const title = titleOverride || reportTitle(type);

  function handlePrint() {
    printNode(title, printRef.current);
  }

  return (
    <Modal title={title} onClose={onClose} size="lg">
      <div className="print-preview-toolbar">
        <button type="button" className="btn btn-primary btn-sm" onClick={handlePrint}>
          <Printer size={14} /> Print
        </button>
      </div>
      <div ref={printRef} className="printable-report-content">
        <ReportBody type={type} data={data} generatedBy={generatedBy} />
      </div>
    </Modal>
  );
}

function reportTitle(type) {
  switch (type) {
    case "sales_invoice":
      return "Sales Invoice";
    case "sales_receipt":
      return "Sales Receipt";
    case "return_receipt":
      return "Return Receipt";
    case "damage_report":
      return "Damage Report";
    case "inventory_report":
      return "Inventory Report";
    case "sales_report":
      return "Sales Report";
    default:
      return "Document";
  }
}

function ReportBody({ type, data, generatedBy }) {
  switch (type) {
    case "sales_invoice":
      return <OrderDoc order={data} title="Sales Invoice" generatedBy={generatedBy} />;
    case "sales_receipt":
      return <OrderDoc order={data} title="Sales Receipt" generatedBy={generatedBy} />;
    case "return_receipt":
      return <OrderDoc order={data} title="Return Receipt" generatedBy={generatedBy} showReason />;
    case "damage_report":
      return <DamageDoc damage={data} generatedBy={generatedBy} />;
    case "inventory_report":
      return <InventoryDoc report={data} generatedBy={generatedBy} />;
    case "sales_report":
      return <SalesDoc report={data} generatedBy={generatedBy} />;
    default:
      return <p className="muted">No printable report is available for this record.</p>;
  }
}

function DocHeader({ title, subtitle }) {
  return (
    <div className="doc-header">
      <div className="doc-brand">
        <span className="logo-mighty">MIGHTY</span>
        <span className="logo-clean">CLEAN</span>
      </div>
      <h2>{title}</h2>
      {subtitle && <p className="doc-subtitle">{subtitle}</p>}
    </div>
  );
}

function SignatureLine({ name }) {
  return (
    <div className="signature-block">
      <div className="signature-space" />
      <div className="signature-underline" />
      <div className="signature-name">{name || "—"}</div>
      <div className="signature-label">Generated by</div>
    </div>
  );
}

function OrderDoc({ order, title, generatedBy, showReason }) {
  const lines = order.products || [];
  return (
    <div>
      <DocHeader title={title} subtitle={`Order #${order.displayNumber || order.id}`} />
      <div className="doc-meta">
        <div>
          <strong>Customer</strong> {order.customer}
        </div>
        <div>
          <strong>Handover date</strong> {formatDate(order.handoverDate)}
        </div>
        <div>
          <strong>Date created</strong> {formatDateTime(order.createdAt)}
        </div>
        <div>
          <strong>Status</strong> {order.status}
        </div>
      </div>
      <table className="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Qty</th>
            <th>Unit cost</th>
            <th>Line total</th>
          </tr>
        </thead>
        <tbody>
          {lines.map((line, i) => (
            <tr key={i}>
              <td>{line.name}</td>
              <td>{line.qty}</td>
              <td>₱{Number(line.cost).toFixed(2)}</td>
              <td>₱{(Number(line.cost) * Number(line.qty)).toFixed(2)}</td>
            </tr>
          ))}
          {lines.length === 0 && (
            <tr>
              <td colSpan={4} className="muted" style={{ textAlign: "center" }}>
                No line items.
              </td>
            </tr>
          )}
        </tbody>
      </table>
      <div className="doc-total">Total: ₱{Number(order.totalCost).toFixed(2)}</div>
      {showReason && (
        <div className="doc-reason">
          <strong>Reason for Return</strong>
          <p>{order.returnReason || "—"}</p>
        </div>
      )}
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function DamageDoc({ damage, generatedBy }) {
  return (
    <div>
      <DocHeader title="Damage Report" subtitle={`Report #${damage.id}`} />
      <div className="doc-meta">
        <div>
          <strong>Product</strong> {damage.productName} ({damage.productCode})
        </div>
        <div>
          <strong>Quantity damaged</strong> {damage.quantity}
        </div>
        <div>
          <strong>Issue</strong> {damage.issue}
        </div>
        <div>
          <strong>Reported by</strong> {damage.staffName || "—"}
        </div>
        <div>
          <strong>Date</strong> {formatDateTime(damage.createdAt)}
        </div>
      </div>
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function InventoryDoc({ report, generatedBy }) {
  return (
    <div>
      <DocHeader
        title="Inventory Report"
        subtitle={`Generated ${new Date(report.generatedAt).toLocaleString()}`}
      />
      <p>
        {report.totalProducts} products · Total production cost value ₱
        {report.totalValue.toLocaleString()}
      </p>
      <table className="table">
        <thead>
          <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Category</th>
            <th>Production Cost</th>
            <th>Price</th>
            <th>In Stock</th>
            <th>Available</th>
            <th>Outgoing</th>
          </tr>
        </thead>
        <tbody>
          {report.products.map((p) => (
            <tr key={p.id}>
              <td>{p.code}</td>
              <td>{p.name}</td>
              <td>{p.category}</td>
              <td>₱{p.cost.toFixed(2)}</td>
              <td>₱{p.price.toFixed(2)}</td>
              <td>{p.stock}</td>
              <td>{p.available}</td>
              <td>{p.outgoing}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function SalesDoc({ report, generatedBy }) {
  return (
    <div>
      <DocHeader
        title="Sales Report"
        subtitle={`Generated ${new Date(report.generatedAt).toLocaleString()}`}
      />
      <p>
        {report.totalUnits} units sold · Total revenue ₱{report.totalRevenue.toLocaleString()}
      </p>
      <table className="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Qty</th>
            <th>Unit price</th>
            <th>Total</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {report.sales.map((s, i) => (
            <tr key={`${s.id}-${i}`}>
              <td>
                {s.product_name}
                {s.product_code ? ` (${s.product_code})` : ""}
              </td>
              <td>{s.quantity}</td>
              <td>₱{s.unit_price.toFixed(2)}</td>
              <td>₱{s.total.toFixed(2)}</td>
              <td className="muted">{new Date(s.created_at).toLocaleDateString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <SignatureLine name={generatedBy} />
    </div>
  );
}
