import { createPortal } from "react-dom";
import { X, Printer } from "lucide-react";

export function PrintableReport({ type, data, generatedBy, onClose }) {
  if (!data) return null;

  return createPortal(
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal modal-wide printable-modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header no-print">
          <h3>Preview</h3>
          <div className="row-actions">
            <button className="btn btn-primary btn-sm" onClick={() => window.print()}>
              <Printer size={14} /> Print
            </button>
            <button className="icon-btn icon-btn-neutral" onClick={onClose}>
              <X size={18} />
            </button>
          </div>
        </div>
        <div className="printable-report">
          <ReportBody type={type} data={data} generatedBy={generatedBy} />
        </div>
      </div>
    </div>,
    document.body
  );
}

function ReportBody({ type, data, generatedBy }) {
  switch (type) {
    case "sales_invoice":
      return <OrderDoc order={data} title="Sales Invoice" generatedBy={generatedBy} />;
    case "sales_receipt":
      return <OrderDoc order={data} title="Sales Receipt" generatedBy={generatedBy} />;
    case "return_receipt":
      return <OrderDoc order={data} title="Return Receipt" generatedBy={generatedBy} />;
    case "damage_report":
      return <DamageDoc damage={data} generatedBy={generatedBy} />;
    case "inventory_report":
      return <InventoryDoc report={data} generatedBy={generatedBy} />;
    case "sales_report":
      return <SalesDoc report={data} generatedBy={generatedBy} />;
    case "goods_receipt":
      return <GoodsReceiptDoc receipt={data} generatedBy={generatedBy} />;
    default:
      return <p className="muted">No printable report is available for this record.</p>;
  }
}

export function DocHeader({ title, subtitle }) {
  return (
    <div className="doc-header">
      <div className="doc-brand">
        <span className="logo-mighty">MIGHTY</span>
        <span className="logo-clean">CLEAN</span>
      </div>
      <h2>{title}</h2>
      {subtitle && <p className="muted">{subtitle}</p>}
    </div>
  );
}

export function SignatureLine({ name }) {
  return (
    <div className="signature-block">
      <div className="signature-space" />
      <div className="signature-underline" />
      <div className="signature-name">{name || "—"}</div>
      <div className="muted" style={{ fontSize: 12 }}>
        Generated by
      </div>
    </div>
  );
}

function OrderDoc({ order, title, generatedBy }) {
  return (
    <div>
      <DocHeader title={title} subtitle={`Order #${order.displayNumber || order.id}`} />
      <p>
        <strong>Customer:</strong> {order.customer}
        <br />
        <strong>Date created:</strong>{" "}
        {order.createdAt ? new Date(order.createdAt).toLocaleString() : "—"}
        <br />
        <strong>Status:</strong> {order.status}
      </p>
      <table className="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Qty</th>
            <th>Unit cost</th>
            <th>Line total</th>
          </tr>
        </thead>
        <tbody>
          {(order.products || []).map((line, i) => (
            <tr key={i}>
              <td>{line.name}</td>
              <td>{line.qty}</td>
              <td>₱{Number(line.cost).toFixed(2)}</td>
              <td>₱{(Number(line.cost) * Number(line.qty)).toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p style={{ textAlign: "right", fontWeight: 700 }}>
        Total: ₱{Number(order.totalCost).toFixed(2)}
      </p>
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function DamageDoc({ damage, generatedBy }) {
  return (
    <div>
      <DocHeader title="Damage Report" subtitle={`Report #${damage.id}`} />
      <p>
        <strong>Product:</strong> {damage.productName} ({damage.productCode})
        <br />
        <strong>Quantity damaged:</strong> {damage.quantity}
        <br />
        <strong>Issue:</strong> {damage.issue}
        <br />
        <strong>Reported by:</strong> {damage.staffName || "—"}
        <br />
        <strong>Date:</strong> {damage.createdAt ? new Date(damage.createdAt).toLocaleString() : "—"}
      </p>
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function InventoryDoc({ report, generatedBy }) {
  return (
    <div>
      <DocHeader
        title="Inventory Report"
        subtitle={`Generated ${new Date(report.generatedAt).toLocaleString()}`}
      />
      <p>
        {report.totalProducts} products · Total production cost value ₱
        {report.totalValue.toLocaleString()}
      </p>
      <table className="table">
        <thead>
          <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Category</th>
            <th>Production Cost</th>
            <th>Price</th>
            <th>In Stock</th>
            <th>Available Stock</th>
            <th>Outgoing Stock</th>
          </tr>
        </thead>
        <tbody>
          {report.products.map((p) => (
            <tr key={p.id}>
              <td>{p.code}</td>
              <td>{p.name}</td>
              <td>{p.category}</td>
              <td>₱{p.cost.toFixed(2)}</td>
              <td>₱{p.price.toFixed(2)}</td>
              <td>{p.stock}</td>
              <td>{p.available}</td>
              <td>{p.outgoing}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function SalesDoc({ report, generatedBy }) {
  return (
    <div>
      <DocHeader
        title="Sales Report"
        subtitle={`Generated ${new Date(report.generatedAt).toLocaleString()}`}
      />
      <p>
        {report.totalUnits} units sold · Total revenue ₱{report.totalRevenue.toLocaleString()}
      </p>
      <table className="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Qty</th>
            <th>Unit price</th>
            <th>Total</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          {report.sales.map((s) => (
            <tr key={s.id}>
              <td>
                {s.product_name} ({s.product_code})
              </td>
              <td>{s.quantity}</td>
              <td>₱{s.unit_price.toFixed(2)}</td>
              <td>₱{s.total.toFixed(2)}</td>
              <td className="muted">{new Date(s.created_at).toLocaleDateString()}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <SignatureLine name={generatedBy} />
    </div>
  );
}

function GoodsReceiptDoc({ receipt, generatedBy }) {
  return (
    <div>
      <DocHeader title="Goods Receipt" subtitle={`Receipt #${receipt.id}`} />
      <p>
        <strong>Received by:</strong> {receipt.staffName || "—"}
        <br />
        <strong>Date received:</strong>{" "}
        {receipt.createdAt ? new Date(receipt.createdAt).toLocaleString() : "—"}
      </p>
      <table className="table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Code</th>
            <th>Qty Received</th>
          </tr>
        </thead>
        <tbody>
          {(receipt.products || []).map((line, i) => (
            <tr key={i}>
              <td>{line.name}</td>
              <td>{line.code}</td>
              <td>{line.qty}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p style={{ textAlign: "right", fontWeight: 700 }}>
        Total units received: {receipt.totalQty}
      </p>
      <SignatureLine name={generatedBy} />
    </div>
  );
}